In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5]

In [3]:
listnp = np.array(list1)

In [4]:
list1

[1, 2, 3, 4, 5]

In [5]:
listnp

array([1, 2, 3, 4, 5])

In [6]:
list1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
listnp*2

array([ 2,  4,  6,  8, 10])

In [8]:
list1+20

TypeError: can only concatenate list (not "int") to list

In [10]:
for n in list1:
    print(n+20)

21
22
23
24
25


In [11]:
listnp+20

array([21, 22, 23, 24, 25])

In [12]:
[n+20 for n in list1]

[21, 22, 23, 24, 25]

In [15]:
list2 = []

In [18]:
for n in list1:
    list2.append(n+20)

In [19]:
list2

[21, 22, 23, 24, 25, 21, 22, 23, 24, 25]

In [20]:
np.sqrt(listnp)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [21]:
list3 = [5.8,3.2,5.5,8]

In [22]:
list2np = np.array(list3)

In [24]:
np.ceil(list2np)

array([6., 4., 6., 8.])

In [25]:
np.floor(list2np)

array([5., 3., 5., 8.])

In [32]:
np.around(list2np,0)

array([6., 3., 6., 8.])